---
version: 2.1

default:
  install: &poetry_install
    pkg_manager: poetry
    install_args: --no-ansi --with dev
  filter: &release_filters
    filters:
      tags:
        only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
      branches:
        ignore: /.*/

# ----------------
# Orbs declaration
# ----------------

orbs:
  noos-ci: noosenergy/noos-ci@0.1.17

# --------------
# Pipeline tasks
# --------------

jobs:
  lint_package:
    executor:
      name: noos-ci/default
      tag: 3.11.4
    steps:
      - checkout
      - noos-ci/python_lint_package:
          src_directory: ./dash_mdc_neptune
          <<: *poetry_install

  lint_library:
    executor:
      name: noos-ci/default
      tag: 3.11.4
    steps:
      - checkout
      - run:
          name: Lint JavaScript library
          command: yarn install && yarn lint

  build_library:
    executor:
      name: noos-ci/default
      tag: 3.11.4
    steps:
      - checkout
      - noos-ci/python_configure_venv:
          <<: *poetry_install
      - run:
          name: Build JavaScript library
          command: yarn install && yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dash_mdc_neptune

  test_package:
    executor:
      name: noos-ci/default
      tag: 3.11.4
    steps:
      - checkout
      - attach_workspace:
          at: .
      - noos-ci/python_test_package:
          tests_directory: ./tests
          <<: *poetry_install
      - store_test_results:
          path: ".pytest_results"

  build_wheel:
    executor:
      name: noos-ci/default
      tag: 3.11.4
    steps:
      - checkout
      - attach_workspace:
          at: .
      - noos-ci/python_build_wheel:
          <<: *poetry_install
      - store_artifacts:
          path: dist
          destination: wheel

  publish_wheel:
    executor:
      name: noos-ci/default
      tag: 3.11.4
    steps:
      - checkout
      - attach_workspace:
          at: .
      - noos-ci/python_publish_wheel:
          <<: *poetry_install

# -----------------
# Pipeline workflow
# -----------------

workflows:
  version: 2

  lint_test_build:
    jobs:
      - lint_library
      - build_library:
          requires:
            - lint_library
      - lint_package
      - test_package:
          requires:
            - build_library
      - build_wheel:
          requires:
            - lint_package
            - test_package

  publish:
    jobs:
      - approve_for_publishing:
          type: approval
          <<: *release_filters
      - build_library:
          requires:
            - approve_for_publishing
          <<: *release_filters
      - publish_wheel:
          context: PYPI_SHARED
          requires:
            - build_library
          <<: *release_filters
