---
version: 2.1

# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.1.17


# --------------
# Pipeline tasks
# --------------

jobs:

  lint_package:
    executor:
      name: noos-ci/default
      # tag: 3.8.17
    steps:
      - checkout
      - noos-ci/python_lint_package:
          pkg_manager: poetry
          install_args: --no-ansi --with dev
          src_directory: ./dash_mdc_neptune

  lint_library:
    executor:
      name: noos-ci/default
      # tag: 3.8.17
    steps:
      - checkout
      - run:
          name: Lint JavaScript library
          command: yarn install && yarn lint

  build_library:
    executor:
      name: noos-ci/default
      # tag: 3.8.17
    steps:
      - checkout
      - noos-ci/python_configure_venv:
          pkg_manager: poetry
          install_args: --no-ansi --with dev
      - run:
          name: Build JavaScript library
          command: yarn install && yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dash_mdc_neptune

  test_package:
    executor:
      name: noos-ci/default
      # tag: 3.8.17
    steps:
      - checkout
      - attach_workspace:
          at: .
      - noos-ci/python_test_package:
          pkg_manager: poetry
          install_args: --no-ansi --with dev
          tests_directory: ./tests

  build_wheel:
    executor:
      name: noos-ci/default
      # tag: 3.8.17
    steps:
      - checkout
      - attach_workspace:
          at: .
      - noos-ci/python_build_wheel:
          pkg_manager: poetry
          install_args: --no-ansi --with dev
      - store_artifacts:
          path: dist
          destination: wheel

  publish_wheel:
    executor:
      name: noos-ci/default
      # tag: 3.8.17
    steps:
      - checkout
      - attach_workspace:
          at: .
      - noos-ci/python_publish_wheel:
          pkg_manager: poetry
          install_args: --no-ansi --with dev


# -----------------
# Pipeline workflow
# -----------------

workflows:

  version: 2

  lint_test_build:
    jobs:
      - lint_library
      - build_library:
          requires:
            - lint_library
      - lint_package
      - test_package:
          requires:
            - build_library
      - build_wheel:
          requires:
            - lint_package
            - test_package

  publish:
    jobs:
      - approve_for_publishing:
          type: approval
          filters:
            tags:
              # ONLY git tag compliant format: e.g. `0.0.1-alpha.01`
              only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
            branches:
              ignore: /.*/
      - build_library:
          requires:
            - approve_for_publishing
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
            branches:
              ignore: /.*/
      - publish_wheel:
          context: PYPI_SHARED
          requires:
            - build_library
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
            branches:
              ignore: /.*/
